name: Build, Lint, Test and Dockerize

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    # - name: Run tests
    #   run: npm test

    - name: Build Next.js app
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (no push)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: false
        tags:

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: us-central1-docker.pkg.dev/ntalks-466823/ntalks-repo/next-app:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy next-app \
          --image us-central1-docker.pkg.dev/ntalks-466823/ntalks-repo/next-app:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
